package calypsox.tk.report;


public enum MaterialTermsColumns {
	USI,
	TRADEPARTYVAL_1,
	CFTC_CATEGORY_1,
	US_PERSON_1,
	TRADEPARTYVAL_2,
	CFTC_CATEGORY_2,
	US_PERSON_2,
	UPI,
	MULTI_ASSET,
	ASSETCLASS,
	SECONDARY_ASSET_CLASS,
	REGULATED_BY,
	ADDITIONAL_REPOSITORY,
	EXECUTION_VENUE_PRF,
	EXECUTION_VENUE,
	BUYER_LEI,
	SELLER_LEI,
	REFERENCE_ENTITY,
	UNDERL_ASSET,
	START_DATE,
	END_DATE,
	PRICE,
	NOTIONAL_AMOUNT,
	NOTIONAL_CURRENCY,
	PAY_FREQ_PERIOD,
	PAY_FREQ_PERIOD_MULT,
	UPFRONT_FEE,
	UPFRONT_CURRENCY,
	COLLATERALIZED,
	BACK_OFFICE_ID,
	BACK_OFFICE_SYSTEM,
	FRONT_OFFICE_ID,
	REC_DATE,
	BRANCH,
	FEED,
	STRUCTURE_ID,
	STRUCTURE_TYPE,
	INSTRUMENT,
	SOURCE_SYSTEM_FO,
	SHORT_NAME,
	PORTFOLIO,
	TRADE_DATE,
	INDIVIDUAL_INDICATOR,
	RISK_SECTOR_CTY,
	UTI,
	INTERNAL_CODE,
	MARKIT_ID,
	NOMINAL_CURR,
	LIVE_NOMINAL,
	ORIG_NOMINAL,
	CONFIRM_SYSTEM,
	UNADJUSTED_MATDATE,
	COUNTERPARTY_NAME,
	DFA_REPORTING,
	EMIR_REPORTING,
	SWAP_DEALER_ID,
	CRD_EMIR_CLEARING_CATEGORY,
	EMIR_FULL_DELEGATION,
	TRADE_STATUS,
	INSTRUMENT_TYPE,
	RESIDENCE_COUNTRY,
	TRADER,
	SELLER,
	ORIGINAL_COUNTERPARTY,
	ORIG_CPTY_DFA_OWNER_TYPE,
	MTM,
	MTM_CURRENCY;


  /**
   * Get columns method for Material Terms report
   *
   * @return columns
   */
  public static String[] getColumns() {
	  final MaterialTermsColumns[] values = MaterialTermsColumns.values();
	  final String[] result = new String[values.length];
	  for (int i = 0; i < values.length; i++) {
		  result[i] = values[i].toString();
	  }
	  return result;
  }


}
