package calypsox.tk.anacredit.api.copys;

import calypsox.tk.anacredit.api.attributes.*;
import com.calypso.tk.core.Log;

public enum Copy3Columns {

    /* ID.ENTIDAD                       */      ID_ENTIDAD(					    new Numeric(4)),
    /* FECHA.EXTRACION                  */      FECHA_EXTRACCION(  			    new DateString()),
    /* ID.CONTRATO                      */      ID_CONTRATO(        		    new Alpha(50)),
    /* ID.CONTRATO.INTERNO              */      ID_CONTRATO_INTERNO(		    new Alpha(50)),
    /* APLICACION.ORIGEN                */      APLICACION_ORIGEN(  		    new Alpha(4)),
    /* ID.CENTRO.CONTABLE               */      ID_CENTRO_CONTABLE( 		    new Numeric(6)),
    /* CODIGO.VALOR                     */      CODIGO_VALOR(       		    new Alpha(12)),
    /* DECLARADO.CIR.TERCERA.ENTIDAD    */      DECLARADO_CIR_TERCERA_ENTIDAD(	new Alpha(1)),
    /* PAIS.NEGOCIO                     */      PAIS_NEGOCIO(				    new Alpha(4)),
    /* PRODUCTO                         */      PRODUCTO_AC(				    new Alpha(5)),
    /* PRODUCTO.ENTIDAD                 */      PRODUCTO_ENTIDAD(      	    	new Alpha(5)),
    /* ACTIVO.OP.VALORES                */      ACTIVO_OP_VALORES(      		new Alpha(5)),
    /* SUBORDINACION.PRODUCTO           */      SUBORDINACION_PRODUCTO_AC(	    new Alpha(2)),
    /* TIPO.RIESGO.SUBYACENTE           */      TIPO_RIESGO_SUBYACENTE(		    new Alpha(2)),
    /* FINALIDAD                        */      FINALIDAD_AC(	    			new Alpha(4)),
    /* TRAMITE.RECUPERACION             */      TRAMITE_RECUPERACION(   		new Alpha(2)),
    /* PRINCIPAL.INICIAL                */      PRINCIPAL_INICIAL( 	    	new Decimal(13, 2, true)),
    /* LIMITE.INICIAL                   */      LIMITE_INICIAL( 	    	new Decimal(13, 2, true)),
    /* IMPORTE.CONCEDIDO                */      IMPORTE_CONCEDIDO( 	    	new Decimal(13, 2, true)),
    /* FECHA.EMISION.ORIGINACION        */      FECHA_EMISION_ORIGINACION(	    new DateString()),
    /* FECHA.VENCIMIENTO                */      FECHA_VENCIMIENTO(	    		new DateString()),
    /* FECHA.CANCELACION                */      FECHA_CANCELACION(		    	new DateString()),
    /* ORIGEN.OPERACION                 */      ORIGEN_OPERACION( 			    new Alpha(4)),
    /* REFINANCIACION                   */      REFINANCIACION(      			new Alpha(2)),
    /* SUBVENCION.OPERACION             */      SUBVENCION_OPERACION(   		new Alpha(3)),
    /* CANAL.CONTRATACION               */      CANAL_CONTRATACION_AC(	    	new Alpha(3)),
    /* PROVINCIA.NEGOCIO                */      PROVINCIA_NEGOCIO(		    	new Alpha(2)),
    /* ESQUEMA.AMORTIZACION.OPERACIONES */      ESQUEMA_AMORT_OPERACIONES_AC(	new Alpha(2)),
    /* PORCENTAJE.PARTICIPACION.SINDICADOS*/    PORCENT_PARTICIP_SINDICADOS(    new Decimal(3, 5)),
    /* EDIF.FINANC.ESTADO               */      EDIF_FINANC_ESTADO(			    new Alpha(2)),
    /* EDIF.FINANC.LICENCIA             */      EDIF_FINANC_LICENCIA(		    new Alpha(3)),
    /* INMUEBLE.FINANC.NUM.VIVIENDAS    */      INMUEBLE_FINANC_NUM_VIVIENDAS(  new Numeric(13)),
    /* CODIGO.PROMOC.INMOB.FINAN        */      CODIGO_PROMOC_INMOB_FINAN( 	    new Alpha(20)),
    /* DESC.PROMOC.INMOB.FINAN          */      DESC_PROMOC_INMOB_FINAN(    	new Alpha(50)),
    /* MONEDA                           */      MONEDA( 					    new Alpha(3)),
    /* PLAZO.RESIDUAL                   */      PLAZO_RESIDUAL(	    			new Alpha(2)),
    /* TIPO.GARANTIA.REAL.PPAL          */      TIPO_GARANTIA_REAL_PPAL(	    new Alpha(3)),
    /* ORDEN.HIPOTECA                   */      ORDEN_HIPOTECA( 		    	new Numeric(1)),
    /* COBERTURA.GARANTIA.REAL          */      COBERTURA_GARANTIA_REAL(	    new Alpha(2)),
    /* TIPO.GARANTIA.PERSONAL.PPAL      */      TIPO_GARANT_PERSONAL_PPAL_AC(	new Alpha(2)),
    /* COBERTURA.GARANTIA.PERSONAL      */      COBERTURA_GARANTIA_PERSONAL(    new Alpha(2)),
    /* FECHA.PRIMER.INCUMPLIMIENTO      */      FECHA_PRIMER_INCUMPLIMIENTO(    new DateString()),
    /* FECHA.ULTIMO.IMPAGO.INCUMPLIMIENTO*/     FECHA_ULTIMO_IMPAGO_INCUMPLIM( 	new DateString()),
    /* SALDO.DEUDOR.NO.VENCIDO          */      SALDO_DEUDOR_NO_VENCIDO(  	    new Decimal(13 ,2, true)),
    /* SALDO.DEUDOR.VENCIDO             */      SALDO_DEUDOR_VENCIDO(  		    new Decimal(13 ,2, true)),
    /* PRODUCTOS.VENCIDOS               */      PRODUCTOS_VENCIDOS( 		    new Decimal(13 ,2, true)),
    /* PRODUCTOS.DUDOSOS.NO.CONSOLIDADOS*/      PRODUCTOS_DUDOSOS_NO_CONSOLID(new Decimal(13 ,2, true)),
    /* INTERESES.DEMORA.CONSOLIDADOS    */      INTERESES_DEMORA_CONSOLIDADOS(new Decimal(13 ,2, true)),
    /* INTERESES.DEMORA.NO.CONSOLIDADOS */      INTERESES_DEMORA_NO_CONSOLID(new Decimal(13 ,2, true)),
    /* GASTOS.ACTIVADOS                 */      GASTOS_ACTIVADOS(    		    new Decimal(13 ,2, true)),
    /* RESTO.VALOR.CONTABLE.ACTIVOS     */      RESTO_VALOR_CONTABLE_ACTIVOS(   new Decimal(13 ,2, true)),
    /* SALDO.ACREEDOR                   */      SALDO_ACREEDOR(      		    new Decimal(13 ,2, true)),
    /* LIMITE                           */      LIMITE(  					    new Decimal(13 ,2, true)),
    /* DISPONIBLE.INMEDIATO             */      DISPONIBLE_INMEDIATO(  		    new Decimal(13 ,2, true)),
    /* DISPONIBLE.CONDICIONADO          */      DISPONIBLE_CONDICIONADO(  	    new Decimal(13 ,2, true)),
    /* PRINCIPAL.COBRADO.MES.AMORT.CORRIENTE*/  PPAL_COBRADO_MES_AMORT_CORRNT(  new Decimal(13 ,2, true)),
    /* PRINCIPAL.COBRADO.MES.AMORT.ANTICIPADA*/ PPAL_COBRADO_MES_AMORT_ANTICI(  new Decimal(13 ,2, true)),
    /* VAR.DEUDA.COND.PRESC             */      VAR_DEUDA_COND_PRESC(   	    new Decimal(13 ,2, true)),
    /* TIPO.ACT.RECIB.PAGO.MES          */      TIPO_ACT_RECIB_PAGO_MES(    	new Alpha(2)),
    /* REDUC.DEUDA.ACT.RECIB.PAGO.MES   */      REDUC_DEUDA_ACT_RECIB_PAG_MES(	new Decimal(13 ,2, true)),
    /* TIPO.SUBROGACION.MES             */      TIPO_SUBROGACION_MES(   		new Alpha(3)),
    /* REDUC.DEUDA.SUBROGACION.MES      */      REDUC_DEUDA_SUBROGACION_MES(    new Decimal(13 ,2, true)),
    /* TIPO.REFINANC.MES                */      TIPO_REFINANC_MES(  		    new Alpha(2)),
    /* REDUC.DEUDA.REFINANC.MES         */      REDUC_DEUDA_REFINANC_MES(  	    new Decimal(13 ,2, true)),
    /* GESTION.OP.TRANSFERIDA.MES       */      GESTION_OP_TRANSFERIDA_MES(     new Alpha(1)),
    /* IMPORTE.TRANSFERIDO.MES.CI       */      IMPORTE_TRANSFERIDO_MES_CI(     new Decimal(13 ,2, true)),
    /* FECHA.ULTIMO.VENCIMIENTO.INTERESES   */  FECHA_ULTIMO_VTO_INTERESES(     new DateString()),
    /* FECHA.PROXIMO.VENCIMIENTO.INTERESES  */  FECHA_PROXIMO_VTO_INTERESES(    new DateString()),
    /* FECHA.ULTIMO.VENCIMIENTO.PRINICIPAL  */  FECHA_ULTIMO_VTO_PRINICIPAL(    new DateString()),
    /* FECHA.PROXIMO.VENCIMIENTO.PRINCIPAL  */  FECHA_PROXIMO_VTO_PRINCIPAL(    new DateString()),
    /* NUMERO.CUOTAS.IMPAGADAS.PRINCIPAL    */  NUM_CUOTAS_IMPAGADAS_PPAL(      new Numeric(13)),
    /* MODALIDAD.TIPO.INTERES           */      MODALIDAD_TIPO_INTERES_AC(	    new Alpha(3)),
    /* TEDR                                 */  TEDR(  						    new Decimal(3, 4, true)),
    /* INDICE.REFERENCIA                    */  INDICE_REFERENCIA_AC(      	    new Alpha(3)),
    /* SUELO.RENTABILIDAD                   */  SUELO_RENTABILIDAD( 		    new Decimal(3, 5)),
    /* TECHO.RENTABILIDAD                   */  TECHO_RENTABILIDAD(     	    new Decimal(3, 5)),
    /* DIFERENCIAL.SOBRE.INDICE.REFERENCIA  */  DIFERENCIAL_SOBRE_INDICE_REFE(	new Decimal(3, 4, true)),
    /* ID.PERSONA.CONTRAPARTE.DIRECTA       */  ID_PERSONA_CONTRAPARTE_DIRECT(	new Alpha(50)),
    /*  SITUACION.OPERACION.RIESGO.DIRECTO  */  SITUACION_OPE_RIESGO_DIREC_AC(		new Alpha(4)),
    /*  CLASIFICACION.OPER.B3               */  CLASIFICACION_OPER_B3( 		    new Alpha(5)),
    /* COBERTURA.RIESGO.DUDOSO              */  COBERTURA_RIESGO_DUDOSO(    new Decimal (13, 2, true)),
    /* COBERTURA.RIESGO.PAIS                */  COBERTURA_RIESGO_PAIS(		new Decimal (13, 2, true)),
    /* PROVISION.RIESGO.DUDOSO              */  PROVISION_RIESGO_DUDOSO(    new Decimal (13, 2, true)),
    /* PROVISION.RIESGO.PAIS                */  PROVISION_RIESGO_PAIS(    	new Decimal (13, 2, true)),
    /* INTERESES.DEVENGADOS                 */  INTERESES_DEVENGADOS(     	new Decimal (13, 2, true)),
    /*  COMISIONES.PENDIENTES.DEVENGO       */  COMISIONES_PENDIENTES_DEVENGO(new Decimal (13, 2, true)),
    /*  COSTE.TRANSACCION                   */  COSTE_TRANSACCION(          new Decimal (13, 2, true)),
    /* PRIMA.DESCUENTO.ADQUISICION.ASUNCION */  PRIMA_DESCNTO_ADQUIS_ASUNCION( new Decimal (13, 2, true)),
    /* DESCUENTO.POR.DETERIORO              */  DESCUENTO_POR_DETERIORO(    new Decimal (13, 2, true)),
    /* ACTIVOS.VALOR.RAZONABLE              */  ACTIVOS_VALOR_RAZOBL(       new Decimal (13, 2, true)),
    /* ACTIVOS.VALOR.RAZONABLE.RIESGO.CREDITO*/ ACTIVOS_VALOR_RAZOBL_RSGO_CRE(new Decimal (13, 2, true)),
    /* PASIVOS.VALOR.RAZONABLE               */ PASIVOS_VALOR_RAZONABLE(new Decimal (13, 2, true)),
    /* MICRO.COBERTURA                      */  MICRO_COBERTURA(new Decimal (13, 2, true)),
    /* VALOR.RESIDUAL.NO.GARANTIZADO        */  VALOR_RESIDUAL_NO_GARANTIZADO(new Decimal (13, 2, true)),
    /* VALOR.RESIDUAL.COMP.TERCEROS         */  VALOR_RESIDUAL_COMP_TERCEROS(new Decimal (13, 2, true)),
    /* COTIZA                               */  COTIZA(                  			new Alpha(3)),
    /* ENTIDAD.DEPOSITARIA                  */  ENTIDAD_DEPOSITARIA(               	new Alpha(2)),
    /* VALOR.NOMINAL                        */  VALOR_NOMINAL(                      new Decimal (13, 2, true)),
    /* JERARQUIA.VALOR.RAZONABLE            */  JERARQUIA_VALOR_RAZONABLE(			new Numeric(1)),
    /* VALOR.RAZONABLE                      */  VALOR_RAZONABLE(            		new Decimal (13, 2, true)),
    /* SANEAMIENTOS.DIRECTOS.MES            */  SANEAMIENTOS_DIRECTOS_MES(		    new Decimal (13, 2, true)),
    /* INTERESES.COBRADOS.MES               */  INTERESES_COBRADOS_MES(      		new Decimal (13, 2, true)),
    /* NUMERO.OCURRENCIAS                   */  NUMERO_OCURRENCIAS(        			new Decimal (14, 6)),
    /* PORCENTAJE.PARTICIPACION.CAPITAL     */  PORCENTAJE_PARTICI_CAPITAL(    		new Decimal(3, 5)),
    /* IMPORTE.LIQ.COMPRAS.MES              */  IMPORTE_LIQ_COMPRAS_MES(    		new Decimal (13, 2, true)),
    /* IMPORTE.LIQ.VENTAS.MES               */  IMPORTE_LIQ_VENTAS_MES(    			new Decimal (13, 2, true)),
    /* COBERTURA.PERDIDAS.PARTICIPADAS.MES  */  COBERT_PERDIDAS_PARTCIP_MES(        new Decimal (13, 2, true)),
    /* NOCIONAL                             */  NOCIONAL(                           new Decimal (13, 2, true)),
    /* CORRECCIONES.VALOR.VALORES           */  CORRECCIONES_VALOR_VALORES(         new Decimal (13, 2, true)),
    /* PLAZO.ORIGEN.M                       */  PLAZO_ORIGEN_M(                     new Alpha(2)),
    /* OPERACION.NO.DECLARABLE.CIRBE        */  OPERACION_NO_DECLARABLE_CIRBE(      new Alpha(1)),
    /* FECHA.RENOVACION                     */  FECHA_RENOVACION(                 	new DateString()),
    /* TIPO.CODIGO.VALOR                    */  TIPO_CODIGO_VALOR(                  new Alpha(2)),
    /* DIVIDENDOS.DEVENGADOS.MES            */  DIVIDENDOS_DEVENGADOS_MES(          new Decimal (13, 2, true)),
    /* SALDO.CONTINGENTE                    */  SALDO_CONTINGENTE(                  new Decimal (13, 2, true, DataAttribute.SIGNAL_MINUS)),
    /* PRINCIPAL.VENCIDO.MES.SUBVENCIONADO  */  PRINCIPAL_VENCIDO_MES_SUBVENC(      new Decimal (13, 2, true)),
    /* TIPO.TARJETA                         */  TIPO_TARJETA(      new Alpha(1)),
    /* SALDO.DEUDOR.EXCEDIDO.VENCIDO        */  SALDO_DEUDOR_EXCEDIDO_VENCIDO(     new Decimal (13, 2, true)),
    /* CONTRATO.RENEGOCIADO                 */  CONTRATO_RENEGOCIADO(     new Alpha(1)),
    /* PRINCIPAL.VDO.REFIN.PTE.AMORT        */  PRINCIPAL_VDO_REFIN_PTE_AMORT( new Decimal (13, 2, true)),
    /* FECHA.PRIMER.INCUMPLIMIENTO.OP.REFIN */  FECHA_PRIMER_INCUMPL_OP_REFIN(   new DateString()),
    /* PRODUCTO.SUBPRODUCTO                 */  PRODUCTO_SUBPRODUCTO(       new Alpha(6)),
    /* CONOCIMIENTO.GARANTIA.PERS.PPAL      */  CONOCIMIENTO_GARANT_PERS_PPAL(   new Numeric(1)),
    /* SALDO.DEUDOR.DUDOSO.NO.VENCIDO       */  SALDO_DEUDOR_DUDOSO_NO_VENCID( new Decimal (13, 2, true)),
    /* SALDO.DEUDOR.DUDOSO.VENCIDO          */  SALDO_DEUDOR_DUDOSO_VENCIDO( new Decimal (13, 2, true)),
                                                SALDO_DEUDOR_DUDOSO_EXCED_VEN( new Decimal (13, 2, true)),
    /* PRODUCTOS.VENCIDOS.DUDOSOS           */  PRODUCTOS_VENCIDOS_DUDOSOS( new Decimal (13, 2, true)),
    /* INTERESES.DEMORA.CONSOLIDADOS.DUDOSOS*/  INTERESES_DEMORA_CONSOL_DUDOS( new Decimal (13, 2, true)),
    /* RESTO.VALOR.CONTABLE.ACTIVOS.DUDOSO  */  RESTO_VALOR_CONT_ACTVOS_DUDOS(   new Decimal (13, 2, true)),
    /* COBERTURA.RIESGO.NORMAL              */  COBERTURA_RIESGO_NORMAL( new Decimal (13, 2, true)),
    /* INTERESES.DEVENGADOS.DUDOSOS         */  INTERESES_DEVENGADOS_DUDOSOS(   new Decimal (13, 2, true)),
    /* INTERESES.EXCEDIDOS.DEVENGADOS       */  INTERESES_EXCED_DEVENGADO(     new Decimal (13, 2, true)),
    /* INTERESES.EXCEDIDOS.DEVENGADOS.DUDOSOS*/ INTERESES_EXCED_DEVENGADO_DUD( new Decimal (13, 2, true)),
    /* SALDO.CONTINGENTE.DUDOSO             */  SALDO_CONTINGENTE_DUDOSO(  new Decimal (13, 2, true)),
    /* SALDO.CONTINGENTE.VENCIDO            */  SALDO_CONTINGENTE_VENCIDO( new Decimal (13, 2, true)),
    /* SALDO.CONTINGENTE.DUDOSO.VENCIDO     */  SALDO_CONTINGENTE_DUDOSO_VENC(  new Decimal (13, 2, true)),
    /* ESTADO.REFIN.REEST.RENEG             */  ESTADO_REFIN_REEST_RENEG(  new Alpha(2)),
    /*ID.CONTRATO.JURIDICO                  */  ID_CONTRATO_JURIDICO(   new Alpha(50)),
    /* TIPO.CARTERA.IFRS9                   */  TIPO_CARTERA_IFRS9(   new Alpha(5)),
    /* CARTERA.PRUDENCIAL                   */  CARTERA_PRUDENCIAL(       new Alpha(3)),
    /* FECHA.PRIMERA.LIQUIDACION            */  FECHA_PRIMERA_LIQUIDACION(   new DateString()),
    /* PRODUCTO.RECURSO                     */  PRODUCTO_RECURSO(     new Numeric(1)),
    /* INSTRUMENTO.FIDUCIARIO               */  INSTRUMENTO_FIDUCIARIO( new Numeric(1)),
    /* FINANCIACION.PROYECTO                */  FINANCIACION_PROYECTO(    new Alpha(2)),
    /* IMPORTE.RECUPERADO.ACUM.SIT.IMP      */  IMPORT_RECUPERAD_ACUM_SIT_IMP(   new Decimal (13, 2, true)),
    /* FECHA.ESTADO.CUMPLIMIENTO            */  FECHA_ESTADO_CUMPLIMIENTO(  new DateString()),
    /* FECHA.REFIN.REEST                    */  FECHA_REFIN_REEST(       new DateString()),
    /* TIPO.REFERENCIA.VENCIMIENTO          */  TIPO_REFERENCIA_VENCIMIENTO(    new Alpha(3)),
    /* CODIGO.RATIO.REFERENCIA              */  CODIGO_RATIO_REFERENCIA(      new Numeric(3)),
    /* TIPO.REFERENCIA.SUSTITUTIVO          */  TIPO_REFERENCIA_SUSTITUTIVO(  new Alpha(3)),
    /* FRECUENCIA.REVISION.TIPO.INT.PER     */  FREC_REVISION_TIPO_INT_PER(  new Alpha(2)),
    /* PROXIMA.REVISION.TIPO.INTERES        */  PROXIMA_REVISION_TIPO_INTERES(  new DateString()),
    /* FECHA.FINAL.CARENCIA.PRINCIPAL       */  FECHA_FINAL_CARENCIA_PRINCIPAL(    new DateString()),
    /* FRECUENCIA.PAGO.PRINC.INT            */  FRECUENCIA_PAGO_PRINC_INT(   new Alpha(2)),
    /* SALDO.VIVO.NOMINAL                   */  SALDO_VIVO_NOMINAL(    new Decimal (13, 2, true)),
    /* SALDO.DEUDOR.FALLIDO.NO.VENCIDO      */  SALDO_DEUDOR_FALLIDO_NO_VENC(      new Decimal (13, 2, true)),
    /* SALDO.DEUDOR.FALLIDO.VENCIDO         */  SALDO_DEUDOR_FALLIDO_VENCIDO(      new Decimal (13, 2, true)),
    /* IMPORTES.VENCIDOS                    */  IMPORTES_VENCIDOS(        new Decimal (13, 2, true)),
    /* PRODUCTOS.FALLIDOS                   */  PRODUCTOS_FALLIDOS(    new Decimal (13, 2, true)),
    /* FALLIDOS.ACUMULADOS                  */  FALLIDOS_ACUMULADOS(     new Decimal (13, 2, true)),
    /* INTERESES.DEMORA.FALLIDOS            */  INTERESES_DEMORA_FALLIDOS(    new Decimal (13, 2, true)),
    /* GASTOS.EXIGIBLES.FALLIDOS            */  GASTOS_EXIGIBLES_FALLIDOS(       new Decimal (13, 2, true)),
    /* FASE.DETERIORO                       */  FASE_DETERIORO(    new Alpha(2)),
    /*IMPORTE.LIBROS.ACTIVO                 */  IMPORTE_LIBROS_ACTIVO(       new Decimal (13, 2, true)),
    /* COBERTURA.ACUMULADA                  */  COBERTURA_ACUMULADA(         new Decimal (13, 2, true)),
    /* PROVISION.FUERA.BALANCE              */  PROVISION_FUERA_BALANCE(            new Decimal (13, 2, true)),
    /* ACT.VALOR.RAZONABLE.RIESGO.CRED.ANTES.ADQ */ ACT_VAL_RAZ_RIES_CRED_ANT_ADQ(      new Decimal (13, 2, true)),
    /* SALDO.FUERA.BALANCE                  */  SALDO_FUERA_BALANCE(         new Decimal (13, 2, true)),
    /* DERECHOS.REEMBOLSO                   */  DERECHOS_REEMBOLSO(      new Numeric(1)),
    /*TIPO.FUENTE.DE.CARGA                  */  TIPO_FUENTE_DE_CARGA( new Alpha(2)),
    /* FECHA.RENEGOCIACION                  */  FECHA_RENEGOCIACION(       new DateString()),
    /* SITUACION.IMPAGO.OPERACION           */  SITUACION_IMPAGO_OPERACION(  new Alpha(2)),
    /* FECHA.SITUACION.IMPAGO.OPE           */  FECHA_SITUACION_IMPAGO_OPE(    new DateString()),
    /* RECONOCIMIENTO.BALANCE               */  RECONOCIMIENTO_BALANCE(     new Numeric(1)),
    /* SALDO.DEUDOR.EXCEDIDO.NO.VENCIDO     */  SALDO_DEUDOR_EXCEDIDO_NO_VENC(    new Decimal (13, 2, true)),
    /* SALDO.DEUDOR.DUDOSO.EXCEDIDO.NO.VENC */  SALDO_DEUDOR_DUDOSO_EXCEDIDO_NO_VENC (     new Decimal (13, 2, true)), //ATENCION RETERE
    /* MET.CALC.COBERT.RIESGO.NORMAL        */  MET_CALC_COBERT_RIESGO_NORMAL(       new Alpha(2)),
    /* MET.CALC.COBERT.RIESGO.DUDOSO        */  MET_CALC_COBERT_RIESGO_DUDOSO(    new Alpha(2)),
    /* RENOVACION.AUTOMATICA                */  RENOVACION_AUTOMATICA(          new Alpha(1)),
    /* VALOR.RESIDUAL.NO.GARANTIZADO.DUDOSO */  VALOR_RESIDUAL_NO_GARAN_DUDOS(  new Decimal (13, 2, true)),
    /* VALOR_RESIDUAL_COMP_TER_DUDOS        */  VALOR_RESIDUAL_COMP_TER_DUDOS(  new Decimal (13, 2, true)),
    /* PRODUCTOS.DUDOSOS.DEVENGADOS.ORDEN   */  PRODUCTOS_DUDOSOS_DEVEN_ORDEN(   new Decimal (13, 2, true)),
    /* VALOR.ACTUALIZADO.COM.GARANTIAS.CONCEDIDAS*/ VALOR_ACTUAL_COM_GARAN_CONCED(new Decimal (13, 2, true)),
    /* PROVISION.RIESGO.NORMAL              */  PROVISION_RIESGO_NORMAL(        new Decimal (13, 2, true)),
    /* TOTAL.INTERESES.DEVENGADOS.CREDITOS  */  TOTAL_INTERESES_DEVEN_CREDITO(   new Decimal (13, 2, true)),
    /* OTRAS.PERIODIFICACIONES.ACTIVO       */  OTRAS_PERIODIFICACIONES_ACTIV(    new Decimal (13, 2, true)),
    /* FECHA.BAJA.DEF.CIRBE                 */  FECHA_BAJA_DEF_CIRBE(    new DateString()),
    /* SITUACION.OPERATIVA                  */  SITUACION_OPERATIVA(     new Alpha(3)),
    /* ESTADO.CUMPLIMIENTO                  */  ESTADO_CUMPLIMIENTO(    new Alpha(3)),
    /* CONTRATO.SINDICADO                   */  CONTRATO_SINDICADO(  new Alpha(60)),
    /* ID.PERSONA.CONTRAPARTE.DIRECTA.CIR   */  ID_PERSONA_CONTRAPARTE_DIRECTA_CIR(  new Alpha(50)),
    /* TEDR.VENC                            */  TEDR_VENC(    new Decimal (3, 4, true)),
    /* TEDR.DESC.EXC                        */  TEDR_DESC_EXC(  new Decimal (3, 4, true)),
    /* OPERACION.TITULARES.EXONERADOS       */  OPERACION_TITULARES_EXONERADOS(  new Alpha(1)),
    /* FECHA.PRIMER.INCUMPLIMIENTO.SIN.FALL.PARC */ FECHA_PRIMER_INCUMPLIMIENTO_SIN_FALL_PARC( new DateString()),
    /* CLASIF.OPER.ANEJO.IX                 */  CLASSIF_OPER_ANEJO_IX( new Alpha(3)),
    /* FECHA.REFINANCIACION                 */  FECHA_REFINANCIACION( new DateString()),
    /* SIN.DEVENGO.INTERES                  */  SIN_DEVENGO_INTERES(     new Numeric(1)),
    /* FALLIDOS.PARCIALES                   */  FALLIDOS_PARCIALES(  new Decimal (13, 2, true, DataAttribute.FORCE_NULL)),
    /* ENTIDAD.GRUPO.ORIGEN                 */  ENTIDAD_GRUPO_ORIGEN(    new Alpha(15)),
    /* CUENTA.GRUPO                         */  CUENTA_GRUPO(       new Alpha(20)),
    /* SUBCUENTA                            */  SUBCUENTA(         new Alpha(10)),
    /* ID.CENTRO.CONTABLE.A                 */  ID_CENTRO_CONTABLE_A(       new Alpha(10)),
    /* MORATORIA.COVID19                    */  MORATORIA_COVID19(        new Alpha(02)),
    /* FECHA.INICIO.MORATORIA.COVID19       */  FECHA_INICIO_MORATORIA_COVID19(  new DateString()),
    /* FECHA.FIN.MORATORIA.COVID19          */  FECHA_FIN_MORATORIA_COVID19(   new DateString()),
    /* FECHA.MODIFICACION.RDL               */  FECHA_MODIFICACION( 	    	new FILLER(8)),
    /* MODIFICACION.RDL                     */  MODIFICACION( 	    	new FILLER(3)),
    /* AUMENTO.PLAZO                        */  AUMENTO_PLAZO( 	    	new FILLER(1)),
    /* AUMENTO.PLAZO.FECHA                  */  AUMENTO_PLAZO_FECHA( 	    	new FILLER(8)),
    /* PRESTAMOS.PARTICIPATIVOS             */  PRESTAMOS_PARTICIPATIVOS( 	    	new FILLER(1)),
    /* PRESTAMOS.PARTICIPATIVOS.FECHA       */  PRESTAMOS_PARTICIPATIVOS_FECHA( 	    	new FILLER(8)),
    /* REDUCCION.PRINCIPAL                  */  REDUCCION_PRINCIPAL( 	    	new FILLER(1)),
    /* REDUCCION.PRINCIPAL.FECHA            */  REDUCCION_PRINCIPAL_FECHA( 	    	new FILLER(8)),
    /* REDUCCION.PRINCIPAL.IMPORTE.AVALISTA */  REDUCCION_PRINCIPAL_IMPORTE_AVALISTA( 	    	new Decimal(13 ,2, true)),
    /* REDUCCION.PRINCIPAL.AVALES.EJECUTADO */  REDUCCION_PRINCIPAL_AVALES_EJECUTADO( 	    	new Decimal(13 ,2, true)),
    /* ORIGINADO.CON.DETERIORO              */  ORIGINADO_CON_DETERIORO ( new Numeric(1)),
    /* CALCULO.SITUACION.IMPAGO             */  CALCULO_SITUACION_IMPAGO ( new Numeric(1)),
    /* REVOLVING                            */  REVOLVING (new Numeric(1)),
    /* INGRESOS.O                           */  INGRESOS_O (new Decimal(13 ,5, true)),
    /* CANAL.DISTRIBUCION                   */  CANAL_DISTRIBUCION (new Alpha(7)),
    /* OPERACION.PRECONCEDIDA               */  OPERACION_PRECONCEDIDA (new Numeric(1)),
    /* RDL.19.2022.MEDIDA.APLICADA          */  RDL_19_2022_MEDIDA_APLICADA (new Numeric(1)),
    /* RDL.19.2022.FECHA.MEDIDA.APLICADA    */  RDL_19_2022_FECHA_MEDIDA_APLICADA (new DateString()),
    /* RDL.19.2022.DEUDA.PENDIENTE          */  RDL_19_2022_DEUDA_PENDIENTE (new Decimal(13 ,5, true)),
    /* RDL.19.2022.MESES.AMPLIACION.PLAZO   */  RDL_19_2022_MESES_AMPLIACION_PLAZO (new Decimal(3 ,2, false)),
    /* TIPO.INTERES.NOMINAL                 */  TIPO_INTERES_NOMINAL (new Decimal(3 ,10, false)),
    /* AGENTE.O.INTERMEDIARIO               */  AGENTE_O_INTERMEDIARIO (new Alpha(11)),
    /* AGENTE.O.INTERMEDIARIO.ID.PERSONA    */  AGENTE_O_INTERMEDIARIO_ID_PERSONA (new Alpha(50)),


    /* BLANK                                */  FILLER(new FILLER(455)),
    /* VERSION                              */  VERSION( 	    	new Alpha(5)),
    ;

    Attribute _attr ;

    Copy3Columns(Attribute attr) {
        _attr = attr;
    }

    public String parseValue(Object o) {
        try  {
            if (null != o) {

                return  _attr.formatValue(o);
            }
        } catch (Exception e) {
            Log.error(this.name(), toString() + " value :'" + o.toString() +"'", e);

        }
        return null;
    }

    public boolean isFiller() {
        return _attr.getDataType() == DataType.FILLER;
    }

    public String toString() {
        return " " + this.name() + " " + _attr.toString();
    }

}
