//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 11:18:08 AM CET 
//

package calypsox.engine.medusa.utils.xml;

import com.calypso.tk.core.Log;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="botransfer" type="{}botransfer" minOccurs="0"/>
 *         &lt;element name="botransferResult" type="{}botransferResult" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"botransfer", "botransferResult"})
@XmlRootElement(name = "CashManagement")
public class CashManagement {

    protected Botransfer botransfer;
    protected BotransferResult botransferResult;

    /**
     * Gets the value of the botransfer property.
     *
     * @return possible object is {@link Botransfer }
     */
    public Botransfer getBotransfer() {
        return this.botransfer;
    }

    /**
     * Sets the value of the botransfer property.
     *
     * @param value allowed object is {@link Botransfer }
     */
    public void setBotransfer(final Botransfer value) {
        this.botransfer = value;
    }

    /**
     * Gets the value of the botransferResult property.
     *
     * @return possible object is {@link BotransferResult }
     */
    public BotransferResult getBotransferResult() {
        return this.botransferResult;
    }

    /**
     * Sets the value of the botransferResult property.
     *
     * @param value allowed object is {@link BotransferResult }
     */
    public void setBotransferResult(final BotransferResult value) {
        this.botransferResult = value;
    }

    public String marshall() throws Exception {
        final SantMarshaller<CashManagement> xferMarshaller = new SantMarshaller<CashManagement>(
                CashManagement.class.getPackage().getName());
        return xferMarshaller.marshall(this);
    }

    public static CashManagement unMarshall(final String xmlMessage) {

        CashManagement cashManagement = null;

        final SantMarshaller<CashManagement> xferMarshaller = new SantMarshaller<CashManagement>(
                CashManagement.class.getPackage().getName());

        try {
            final XPathHelper helper = new XPathHelper(xmlMessage, false);
            cashManagement = xferMarshaller.unMarshall(helper.getDocument());

        } catch (final Exception e) {
            // TODO Auto-generated catch block
            Log.error(CashManagement.class, e);
        }
        return cashManagement;
    }

}
