//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 11:18:08 AM CET 
//

package calypsox.engine.medusa.utils.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the calypsox.engine.cmuk.bean package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: calypsox.engine.cmuk.bean
     */
    public ObjectFactory() {
        // do nothing
    }

    /**
     * Create an instance of {@link CashManagement }
     */
    public CashManagement createCashManagement() {
        return new CashManagement();
    }

    /**
     * Create an instance of {@link Botransfer }
     */
    public Botransfer createBotransfer() {
        return new Botransfer();
    }

    /**
     * Create an instance of {@link BotransferResult }
     */
    public BotransferResult createBotransferResult() {
        return new BotransferResult();
    }

}
