//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.isban.efs2.webservice;

import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "EFS2WSService", targetNamespace = "http://webservice.efs2.isban.com/", wsdlLocation = "file:wsdl/EFS2WSService.wsdl")
public class EFS2WSService extends Service {

	private final static URL EFS2WSSERVICE_WSDL_LOCATION;
	@SuppressWarnings("unused")
	private final static Logger logger = Logger.getLogger(com.isban.efs2.webservice.EFS2WSService.class.getName());

	static {
		EFS2WSSERVICE_WSDL_LOCATION = Thread.currentThread().getContextClassLoader()
				.getResource("com/isban/efs2/webservice/wsdl/EFS2WSService.wsdl");
	}

	public EFS2WSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public EFS2WSService() {

		super(EFS2WSSERVICE_WSDL_LOCATION, new QName("http://webservice.efs2.isban.com/", "EFS2WSService"));
	}

	/**
	 * 
	 * @return returns EFS2WS
	 */
	@WebEndpoint(name = "EFS2WSPort")
	public EFS2WS getEFS2WSPort() {
		return super.getPort(new QName("http://webservice.efs2.isban.com/", "EFS2WSPort"), EFS2WS.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
	 *            the <code>features</code> parameter will have their default values.
	 * @return returns EFS2WS
	 */
	@WebEndpoint(name = "EFS2WSPort")
	public EFS2WS getEFS2WSPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://webservice.efs2.isban.com/", "EFS2WSPort"), EFS2WS.class, features);
	}

}
