/*
 *
 * Copyright (c) ISBAN: Ingenieria de Software Bancario, S.L.
 * All rights reserved.
 *
 */
package calypsox.tk.report;


/*
 * This is an extension to the default Calypso report, adding few extra columns
 */
public class IBORCollateralConfigReportTemplate extends com.calypso.tk.report.CollateralConfigReportTemplate {

    /**
     * Autogenerated serial UID.
     */
    private static final long serialVersionUID = 8286222040330862960L;
    
    private static final String _TITLE = "IBORCollateralConfig";
    
    //NewColumns
    public static final String ELEGIBLE_CURRENCIES = "ELEGIBLE_CURRENCIES";
    public static final String TYPE_AGREEMENT = "Type of Agreement";
    public static final String INDEX = "INDEX";
    
    protected static final String[] DEFAULT_COLUMNS = { ELEGIBLE_CURRENCIES, TYPE_AGREEMENT, INDEX};

@Override
public void setDefaults() {
    super.setDefaults();
    put("Title", _TITLE);
    setColumns(DEFAULT_COLUMNS);
}
}
