package calypsox.apps.reporting;

import com.calypso.apps.reporting.MarginCallPositionValuationReportTemplatePanel;

public class SantMCallPositionValCreReportTemplatePanel extends MarginCallPositionValuationReportTemplatePanel {
}
