DELETE FROM WFW_TRANSITION WHERE PROCESS_ORG_ID = 0  AND EVENT_CLASS='PSEventTransfer' and status = 'SETTLED' AND PRODUCT_TYPE='G.Bonds'
AND resulting_status='UNSETTLED' ;

DELETE FROM WFW_TRANSITION WHERE PROCESS_ORG_ID = 0  AND EVENT_CLASS='PSEventTransfer' and status = 'UNSETTLED' AND PRODUCT_TYPE='G.Bonds'
AND resulting_status='FAILED' ;