//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actnTypType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actnTypType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="20"/>
 *     &lt;enumeration value="BIBL"/>
 *     &lt;enumeration value="BIRL"/>
 *     &lt;enumeration value="INS"/>
 *     &lt;enumeration value="DEL"/>
 *     &lt;enumeration value="BLOCK"/>
 *     &lt;enumeration value="RELEASE"/>
 *     &lt;enumeration value="PARTIAL RELEASE"/>
 *     &lt;enumeration value="LINK"/>
 *     &lt;enumeration value="UNLINK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actnTypType")
@XmlEnum
public enum ActnTypType {

    BIBL("BIBL"),
    BIRL("BIRL"),
    INS("INS"),
    DEL("DEL"),
    BLOCK("BLOCK"),
    RELEASE("RELEASE"),
    @XmlEnumValue("PARTIAL RELEASE")
    PARTIAL_RELEASE("PARTIAL RELEASE"),
    LINK("LINK"),
    UNLINK("UNLINK");
    private final String value;

    ActnTypType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActnTypType fromValue(String v) {
        for (ActnTypType c: ActnTypType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
