//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for caSettlRunType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="caSettlRunType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="5"/>
 *     &lt;enumeration value="DD1"/>
 *     &lt;enumeration value="DD2"/>
 *     &lt;enumeration value="NTS"/>
 *     &lt;enumeration value="T2S"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "caSettlRunType")
@XmlEnum
public enum CaSettlRunType {

    @XmlEnumValue("DD1")
    DD_1("DD1"),
    @XmlEnumValue("DD2")
    DD_2("DD2"),
    NTS("NTS"),
    @XmlEnumValue("T2S")
    T_2_S("T2S");
    private final String value;

    CaSettlRunType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CaSettlRunType fromValue(String v) {
        for (CaSettlRunType c: CaSettlRunType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
