//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cashSettlLocType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cashSettlLocType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="3"/>
 *     &lt;enumeration value="ANA"/>
 *     &lt;enumeration value="BAR"/>
 *     &lt;enumeration value="BBK"/>
 *     &lt;enumeration value="BNY"/>
 *     &lt;enumeration value="BOA"/>
 *     &lt;enumeration value="BTM"/>
 *     &lt;enumeration value="CBL"/>
 *     &lt;enumeration value="CIT"/>
 *     &lt;enumeration value="CNY"/>
 *     &lt;enumeration value="DBL"/>
 *     &lt;enumeration value="DBT"/>
 *     &lt;enumeration value="EOC"/>
 *     &lt;enumeration value="ESC"/>
 *     &lt;enumeration value="HBY"/>
 *     &lt;enumeration value="HSB"/>
 *     &lt;enumeration value="JPC"/>
 *     &lt;enumeration value="JPG"/>
 *     &lt;enumeration value="RBN"/>
 *     &lt;enumeration value="RBS"/>
 *     &lt;enumeration value="SMB"/>
 *     &lt;enumeration value="SNB"/>
 *     &lt;enumeration value="UBS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cashSettlLocType")
@XmlEnum
public enum CashSettlLocType {

    ANA,
    BAR,
    BBK,
    BNY,
    BOA,
    BTM,
    CBL,
    CIT,
    CNY,
    DBL,
    DBT,
    EOC,
    ESC,
    HBY,
    HSB,
    JPC,
    JPG,
    RBN,
    RBS,
    SMB,
    SNB,
    UBS;

    public String value() {
        return name();
    }

    public static CashSettlLocType fromValue(String v) {
        return valueOf(v);
    }

}
