//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cashSettlRunType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cashSettlRunType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="5"/>
 *     &lt;enumeration value="NTP"/>
 *     &lt;enumeration value="DTP1"/>
 *     &lt;enumeration value="DTP2"/>
 *     &lt;enumeration value="DTP3"/>
 *     &lt;enumeration value="DTP4"/>
 *     &lt;enumeration value="DTP5"/>
 *     &lt;enumeration value="DTP6"/>
 *     &lt;enumeration value="ADD1"/>
 *     &lt;enumeration value="MISC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cashSettlRunType")
@XmlEnum
public enum CashSettlRunType {

    NTP("NTP"),
    @XmlEnumValue("DTP1")
    DTP_1("DTP1"),
    @XmlEnumValue("DTP2")
    DTP_2("DTP2"),
    @XmlEnumValue("DTP3")
    DTP_3("DTP3"),
    @XmlEnumValue("DTP4")
    DTP_4("DTP4"),
    @XmlEnumValue("DTP5")
    DTP_5("DTP5"),
    @XmlEnumValue("DTP6")
    DTP_6("DTP6"),
    @XmlEnumValue("ADD1")
    ADD_1("ADD1"),
    MISC("MISC");
    private final String value;

    CashSettlRunType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CashSettlRunType fromValue(String v) {
        for (CashSettlRunType c: CashSettlRunType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
