//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for infoListType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="infoListType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="50"/>
 *     &lt;enumeration value="BUY-IN OR CASH SETTLED"/>
 *     &lt;enumeration value="GROSS DELIVERY INFORMATION"/>
 *     &lt;enumeration value="NET DELIVERY INFORMATION"/>
 *     &lt;enumeration value="REPO BUY-IN OR REPO CASH SETTLED"/>
 *     &lt;enumeration value="REPO GROSS DELIVERY INFORMATION"/>
 *     &lt;enumeration value="REPO NET DELIVERY INFORMATION"/>
 *     &lt;enumeration value="REPO OFFSET BLOCK INFORMATION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "infoListType")
@XmlEnum
public enum InfoListType {

    @XmlEnumValue("BUY-IN OR CASH SETTLED")
    BUY_IN_OR_CASH_SETTLED("BUY-IN OR CASH SETTLED"),
    @XmlEnumValue("GROSS DELIVERY INFORMATION")
    GROSS_DELIVERY_INFORMATION("GROSS DELIVERY INFORMATION"),
    @XmlEnumValue("NET DELIVERY INFORMATION")
    NET_DELIVERY_INFORMATION("NET DELIVERY INFORMATION"),
    @XmlEnumValue("REPO BUY-IN OR REPO CASH SETTLED")
    REPO_BUY_IN_OR_REPO_CASH_SETTLED("REPO BUY-IN OR REPO CASH SETTLED"),
    @XmlEnumValue("REPO GROSS DELIVERY INFORMATION")
    REPO_GROSS_DELIVERY_INFORMATION("REPO GROSS DELIVERY INFORMATION"),
    @XmlEnumValue("REPO NET DELIVERY INFORMATION")
    REPO_NET_DELIVERY_INFORMATION("REPO NET DELIVERY INFORMATION"),
    @XmlEnumValue("REPO OFFSET BLOCK INFORMATION")
    REPO_OFFSET_BLOCK_INFORMATION("REPO OFFSET BLOCK INFORMATION");
    private final String value;

    InfoListType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InfoListType fromValue(String v) {
        for (InfoListType c: InfoListType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
