//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for instTypCodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="instTypCodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="3"/>
 *     &lt;enumeration value="EQU"/>
 *     &lt;enumeration value="SUB"/>
 *     &lt;enumeration value="XTF"/>
 *     &lt;enumeration value="BON"/>
 *     &lt;enumeration value="FUN"/>
 *     &lt;enumeration value="ADR"/>
 *     &lt;enumeration value="GDR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "instTypCodType")
@XmlEnum
public enum InstTypCodType {

    EQU,
    SUB,
    XTF,
    BON,
    FUN,
    ADR,
    GDR;

    public String value() {
        return name();
    }

    public static InstTypCodType fromValue(String v) {
        return valueOf(v);
    }

}
