//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the calypsox.repoccp.model.eurex package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tc800_QNAME = new QName("http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases", "tc800");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: calypsox.repoccp.model.eurex
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tc800Type }
     * 
     */
    public Tc800Type createTc800Type() {
        return new Tc800Type();
    }

    /**
     * Create an instance of {@link Tc800Grp5Type }
     * 
     */
    public Tc800Grp5Type createTc800Grp5Type() {
        return new Tc800Grp5Type();
    }

    /**
     * Create an instance of {@link Tc800KeyGrp3Type }
     * 
     */
    public Tc800KeyGrp3Type createTc800KeyGrp3Type() {
        return new Tc800KeyGrp3Type();
    }

    /**
     * Create an instance of {@link Tc800KeyGrp7Type }
     * 
     */
    public Tc800KeyGrp7Type createTc800KeyGrp7Type() {
        return new Tc800KeyGrp7Type();
    }

    /**
     * Create an instance of {@link Tc800Grp1Type }
     * 
     */
    public Tc800Grp1Type createTc800Grp1Type() {
        return new Tc800Grp1Type();
    }

    /**
     * Create an instance of {@link Tc800Grp6Type }
     * 
     */
    public Tc800Grp6Type createTc800Grp6Type() {
        return new Tc800Grp6Type();
    }

    /**
     * Create an instance of {@link Tc800GrpType }
     * 
     */
    public Tc800GrpType createTc800GrpType() {
        return new Tc800GrpType();
    }

    /**
     * Create an instance of {@link Tc800KeyGrp4Type }
     * 
     */
    public Tc800KeyGrp4Type createTc800KeyGrp4Type() {
        return new Tc800KeyGrp4Type();
    }

    /**
     * Create an instance of {@link Tc800Grp2Type }
     * 
     */
    public Tc800Grp2Type createTc800Grp2Type() {
        return new Tc800Grp2Type();
    }

    /**
     * Create an instance of {@link RptHdrType }
     * 
     */
    public RptHdrType createRptHdrType() {
        return new RptHdrType();
    }

    /**
     * Create an instance of {@link Tc800KeyGrp1Type }
     * 
     */
    public Tc800KeyGrp1Type createTc800KeyGrp1Type() {
        return new Tc800KeyGrp1Type();
    }

    /**
     * Create an instance of {@link Tc800Grp3Type }
     * 
     */
    public Tc800Grp3Type createTc800Grp3Type() {
        return new Tc800Grp3Type();
    }

    /**
     * Create an instance of {@link Tc800KeyGrpType }
     * 
     */
    public Tc800KeyGrpType createTc800KeyGrpType() {
        return new Tc800KeyGrpType();
    }

    /**
     * Create an instance of {@link Tc800Grp7Type }
     * 
     */
    public Tc800Grp7Type createTc800Grp7Type() {
        return new Tc800Grp7Type();
    }

    /**
     * Create an instance of {@link Tc800KeyGrp5Type }
     * 
     */
    public Tc800KeyGrp5Type createTc800KeyGrp5Type() {
        return new Tc800KeyGrp5Type();
    }

    /**
     * Create an instance of {@link Tc800RecType }
     * 
     */
    public Tc800RecType createTc800RecType() {
        return new Tc800RecType();
    }

    /**
     * Create an instance of {@link Tc800Grp4Type }
     * 
     */
    public Tc800Grp4Type createTc800Grp4Type() {
        return new Tc800Grp4Type();
    }

    /**
     * Create an instance of {@link Tc800KeyGrp2Type }
     * 
     */
    public Tc800KeyGrp2Type createTc800KeyGrp2Type() {
        return new Tc800KeyGrp2Type();
    }

    /**
     * Create an instance of {@link Tc800KeyGrp6Type }
     * 
     */
    public Tc800KeyGrp6Type createTc800KeyGrp6Type() {
        return new Tc800KeyGrp6Type();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tc800Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases", name = "tc800")
    public JAXBElement<Tc800Type> createTc800(Tc800Type value) {
        return new JAXBElement<Tc800Type>(_Tc800_QNAME, Tc800Type.class, null, value);
    }

}
