//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for performedByType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="performedByType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="11"/>
 *     &lt;enumeration value="STL-INS-DAT"/>
 *     &lt;enumeration value="EUREX"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "performedByType")
@XmlEnum
public enum PerformedByType {

    @XmlEnumValue("STL-INS-DAT")
    STL_INS_DAT("STL-INS-DAT"),
    EUREX("EUREX");
    private final String value;

    PerformedByType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PerformedByType fromValue(String v) {
        for (PerformedByType c: PerformedByType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
