//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rpoTrdTypType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rpoTrdTypType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="4"/>
 *     &lt;enumeration value="GC"/>
 *     &lt;enumeration value="GCOP"/>
 *     &lt;enumeration value="GCOV"/>
 *     &lt;enumeration value="GCVA"/>
 *     &lt;enumeration value="SP"/>
 *     &lt;enumeration value="SPOP"/>
 *     &lt;enumeration value="SPOV"/>
 *     &lt;enumeration value="SPVA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rpoTrdTypType")
@XmlEnum
public enum RpoTrdTypType {

    GC,
    GCOP,
    GCOV,
    GCVA,
    SP,
    SPOP,
    SPOV,
    SPVA;

    public String value() {
        return name();
    }

    public static RpoTrdTypType fromValue(String v) {
        return valueOf(v);
    }

}
