//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for rptHdrType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rptHdrType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="exchNam" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}exchNamType"/>
 *         &lt;element name="envText" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}envTextType"/>
 *         &lt;element name="rptCod" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}rptCodType"/>
 *         &lt;element name="rptNam" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}rptNamType"/>
 *         &lt;element name="rptFlexKey" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}rptFlexKeyType" minOccurs="0"/>
 *         &lt;element name="membId" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}membIdType" minOccurs="0"/>
 *         &lt;element name="membLglNam" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}membLglNamType" minOccurs="0"/>
 *         &lt;element name="rptPrntEffDat" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}rptPrntEffDatType"/>
 *         &lt;element name="rptPrntEffTim" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}rptPrntEffTimType" minOccurs="0"/>
 *         &lt;element name="rptPrntRunDat" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}rptPrntRunDatType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rptHdrType", propOrder = {
    "exchNam",
    "envText",
    "rptCod",
    "rptNam",
    "rptFlexKey",
    "membId",
    "membLglNam",
    "rptPrntEffDat",
    "rptPrntEffTim",
    "rptPrntRunDat"
})
public class RptHdrType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ExchNamType exchNam;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EnvTextType envText;
    @XmlElement(required = true)
    protected String rptCod;
    @XmlElement(required = true)
    protected String rptNam;
    protected String rptFlexKey;
    protected String membId;
    protected String membLglNam;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar rptPrntEffDat;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar rptPrntEffTim;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar rptPrntRunDat;

    /**
     * Gets the value of the exchNam property.
     * 
     * @return
     *     possible object is
     *     {@link ExchNamType }
     *     
     */
    public ExchNamType getExchNam() {
        return exchNam;
    }

    /**
     * Sets the value of the exchNam property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchNamType }
     *     
     */
    public void setExchNam(ExchNamType value) {
        this.exchNam = value;
    }

    /**
     * Gets the value of the envText property.
     * 
     * @return
     *     possible object is
     *     {@link EnvTextType }
     *     
     */
    public EnvTextType getEnvText() {
        return envText;
    }

    /**
     * Sets the value of the envText property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvTextType }
     *     
     */
    public void setEnvText(EnvTextType value) {
        this.envText = value;
    }

    /**
     * Gets the value of the rptCod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptCod() {
        return rptCod;
    }

    /**
     * Sets the value of the rptCod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptCod(String value) {
        this.rptCod = value;
    }

    /**
     * Gets the value of the rptNam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptNam() {
        return rptNam;
    }

    /**
     * Sets the value of the rptNam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptNam(String value) {
        this.rptNam = value;
    }

    /**
     * Gets the value of the rptFlexKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptFlexKey() {
        return rptFlexKey;
    }

    /**
     * Sets the value of the rptFlexKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptFlexKey(String value) {
        this.rptFlexKey = value;
    }

    /**
     * Gets the value of the membId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMembId() {
        return membId;
    }

    /**
     * Sets the value of the membId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMembId(String value) {
        this.membId = value;
    }

    /**
     * Gets the value of the membLglNam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMembLglNam() {
        return membLglNam;
    }

    /**
     * Sets the value of the membLglNam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMembLglNam(String value) {
        this.membLglNam = value;
    }

    /**
     * Gets the value of the rptPrntEffDat property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRptPrntEffDat() {
        return rptPrntEffDat;
    }

    /**
     * Sets the value of the rptPrntEffDat property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRptPrntEffDat(XMLGregorianCalendar value) {
        this.rptPrntEffDat = value;
    }

    /**
     * Gets the value of the rptPrntEffTim property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRptPrntEffTim() {
        return rptPrntEffTim;
    }

    /**
     * Sets the value of the rptPrntEffTim property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRptPrntEffTim(XMLGregorianCalendar value) {
        this.rptPrntEffTim = value;
    }

    /**
     * Gets the value of the rptPrntRunDat property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRptPrntRunDat() {
        return rptPrntRunDat;
    }

    /**
     * Sets the value of the rptPrntRunDat property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRptPrntRunDat(XMLGregorianCalendar value) {
        this.rptPrntRunDat = value;
    }

}
