//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settlStatDlvIdType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="settlStatDlvIdType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="20"/>
 *     &lt;enumeration value="FULLY SETTLED"/>
 *     &lt;enumeration value="PARTIALLY SETTLED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "settlStatDlvIdType")
@XmlEnum
public enum SettlStatDlvIdType {

    @XmlEnumValue("FULLY SETTLED")
    FULLY_SETTLED("FULLY SETTLED"),
    @XmlEnumValue("PARTIALLY SETTLED")
    PARTIALLY_SETTLED("PARTIALLY SETTLED");
    private final String value;

    SettlStatDlvIdType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SettlStatDlvIdType fromValue(String v) {
        for (SettlStatDlvIdType c: SettlStatDlvIdType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
