//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * TC800 Repo Trade Confirmation Report
 * 
 * <p>Java class for tc800Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tc800Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rptHdr" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}rptHdrType"/>
 *         &lt;element name="tc800Grp" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}tc800GrpType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tc800Type", propOrder = {
    "rptHdr",
    "tc800Grp"
})
@XmlRootElement(name="tc800")
public class Tc800Type {

    @XmlElement(required = true)
    protected RptHdrType rptHdr;
    protected List<Tc800GrpType> tc800Grp;

    /**
     * Gets the value of the rptHdr property.
     * 
     * @return
     *     possible object is
     *     {@link RptHdrType }
     *     
     */
    public RptHdrType getRptHdr() {
        return rptHdr;
    }

    /**
     * Sets the value of the rptHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link RptHdrType }
     *     
     */
    public void setRptHdr(RptHdrType value) {
        this.rptHdr = value;
    }

    /**
     * Gets the value of the tc800Grp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tc800Grp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTc800Grp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tc800GrpType }
     * 
     * 
     */
    public List<Tc800GrpType> getTc800Grp() {
        if (tc800Grp == null) {
            tc800Grp = new ArrayList<Tc800GrpType>();
        }
        return this.tc800Grp;
    }

}
