//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tc800KeyGrp2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tc800KeyGrp2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="settlCurrency" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}settlCurrencyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tc800KeyGrp2Type", propOrder = {
    "settlCurrency"
})
public class Tc800KeyGrp2Type {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected SettlCurrencyType settlCurrency;

    /**
     * Gets the value of the settlCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link SettlCurrencyType }
     *     
     */
    public SettlCurrencyType getSettlCurrency() {
        return settlCurrency;
    }

    /**
     * Sets the value of the settlCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlCurrencyType }
     *     
     */
    public void setSettlCurrency(SettlCurrencyType value) {
        this.settlCurrency = value;
    }

}
