//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tc800GrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tc800GrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tc800KeyGrp" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}tc800KeyGrpType"/>
 *         &lt;element name="tc800Grp1" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}tc800Grp1Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tc800GrpType", propOrder = {
    "tc800KeyGrp",
    "tc800Grp1"
})
public class Tc800GrpType {

    @XmlElement(required = true)
    protected Tc800KeyGrpType tc800KeyGrp;
    @XmlElement(required = true)
    protected List<Tc800Grp1Type> tc800Grp1;

    /**
     * Gets the value of the tc800KeyGrp property.
     * 
     * @return
     *     possible object is
     *     {@link Tc800KeyGrpType }
     *     
     */
    public Tc800KeyGrpType getTc800KeyGrp() {
        return tc800KeyGrp;
    }

    /**
     * Sets the value of the tc800KeyGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tc800KeyGrpType }
     *     
     */
    public void setTc800KeyGrp(Tc800KeyGrpType value) {
        this.tc800KeyGrp = value;
    }

    /**
     * Gets the value of the tc800Grp1 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tc800Grp1 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTc800Grp1().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tc800Grp1Type }
     * 
     * 
     */
    public List<Tc800Grp1Type> getTc800Grp1() {
        if (tc800Grp1 == null) {
            tc800Grp1 = new ArrayList<Tc800Grp1Type>();
        }
        return this.tc800Grp1;
    }

}
