//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tc800KeyGrp1Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tc800KeyGrp1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="settlLoc" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}settlLocType"/>
 *         &lt;element name="settlAcct" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}settlAcctType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tc800KeyGrp1Type", propOrder = {
    "settlLoc",
    "settlAcct"
})
public class Tc800KeyGrp1Type {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected SettlLocType settlLoc;
    @XmlElement(required = true)
    protected String settlAcct;

    /**
     * Gets the value of the settlLoc property.
     * 
     * @return
     *     possible object is
     *     {@link SettlLocType }
     *     
     */
    public SettlLocType getSettlLoc() {
        return settlLoc;
    }

    /**
     * Sets the value of the settlLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlLocType }
     *     
     */
    public void setSettlLoc(SettlLocType value) {
        this.settlLoc = value;
    }

    /**
     * Gets the value of the settlAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlAcct() {
        return settlAcct;
    }

    /**
     * Sets the value of the settlAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlAcct(String value) {
        this.settlAcct = value;
    }

}
