//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 03:45:16 PM BST 
//


package calypsox.repoccp.model.eurex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tc800Grp3Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tc800Grp3Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tc800KeyGrp3" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}tc800KeyGrp3Type"/>
 *         &lt;element name="instTypCod" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}instTypCodType"/>
 *         &lt;element name="tc800Grp4" type="{http://www.eurex.com/ec-en/support/initiatives/c7-scs-releases}tc800Grp4Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tc800Grp3Type", propOrder = {
    "tc800KeyGrp3",
    "instTypCod",
    "tc800Grp4"
})
public class Tc800Grp3Type {

    @XmlElement(required = true)
    protected Tc800KeyGrp3Type tc800KeyGrp3;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected InstTypCodType instTypCod;
    @XmlElement(required = true)
    protected List<Tc800Grp4Type> tc800Grp4;

    /**
     * Gets the value of the tc800KeyGrp3 property.
     * 
     * @return
     *     possible object is
     *     {@link Tc800KeyGrp3Type }
     *     
     */
    public Tc800KeyGrp3Type getTc800KeyGrp3() {
        return tc800KeyGrp3;
    }

    /**
     * Sets the value of the tc800KeyGrp3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tc800KeyGrp3Type }
     *     
     */
    public void setTc800KeyGrp3(Tc800KeyGrp3Type value) {
        this.tc800KeyGrp3 = value;
    }

    /**
     * Gets the value of the instTypCod property.
     * 
     * @return
     *     possible object is
     *     {@link InstTypCodType }
     *     
     */
    public InstTypCodType getInstTypCod() {
        return instTypCod;
    }

    /**
     * Sets the value of the instTypCod property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstTypCodType }
     *     
     */
    public void setInstTypCod(InstTypCodType value) {
        this.instTypCod = value;
    }

    /**
     * Gets the value of the tc800Grp4 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tc800Grp4 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTc800Grp4().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tc800Grp4Type }
     * 
     * 
     */
    public List<Tc800Grp4Type> getTc800Grp4() {
        if (tc800Grp4 == null) {
            tc800Grp4 = new ArrayList<Tc800Grp4Type>();
        }
        return this.tc800Grp4;
    }

}
